databases:
  - name: ojtriv
    databaseName: ojtriv
    user: ojtriv

services:
  - type: web
    name: ojtriv
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ojtriv
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false