databases:
  - name: TRIVIAAPPPROJECTOJV
    databaseName: leaderboard
    user: triviaoj

services:
  - type: web
    name: TRIVIAAPPPROJECTOJV
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: TRIVIAAPPPROJECTOJV
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false